vich_uploader:
    db_driver: orm

    # mappings:
    #     image:
    #         uri_prefix: asset/image/uploads
    #         upload_destination: '%kernel.project_dir%/public/images/uploads'
    #         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


    #         inject_on_load: false
    #         delete_on_update: true
    #         delete_on_remove: true
            